import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { Providers } from "@/app/providers";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";

import { Navbar } from "@/components/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <Providers> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
        {/* </Providers> */}
      </body>
    </html>
  );
}
